### ISSUE TITLE
POST /applications/:id/watch

### ISSUE THREAD

**Issue by amirsabersharifi** [Vyrent/vyrent_env#24]
add a watch to the application. if admin is adding this watch then the application source should be admin. if the user it self then it should be user.

Only applications which are not submitted(draft) are able to add watch to.

**Comment by big-kahuna-burger** [comment]
missing :id: in title?

Shouldn't it be ```POST /applications/:id/watch/:id``` where the last one is watch_id?

**Comment by amirsabersharifi** [comment]
TBH, both can be correct, but so far what I usually saw as the standard for RESTful APIs is that they don't put last ID for post request. because it shows the watch is there, ID is used for get, put and delete on last element in path

**Comment by big-kahuna-burger** [comment]
Then :id: is going to be passed trough event?

**Comment by amirsabersharifi** [comment]
Yes
