### ISSUE TITLE
Create API Calls modules

### ISSUE THREAD

**Issue by amirsabersharifi** [Vyrent/vyrent_env#8]
So there will be files which are a set of actions to service one API call. And then these API calls will get put in index.js and get packaged for Lambda function of AWS. We need to start creating a structure to add these to system and a way to test them. For every lambda functions one of these API calls will get triggered.

**Comment by big-kahuna-burger** [comment]
My idea for testing this is to use swagger spec combined with some tooling.
Swagger node to run API locally, and maybe use [Swagger test templates](https://www.npmjs.com/package/swagger-test-templates) to generate request templates.

**Comment by amirsabersharifi** [comment]
I like the idea of swagger. considering that API gateway of amazon is able to provide us with swagger of the API calls. how do you imagine to do this in more details?
